uno, dos, tres, cuatro = 1,2,4,5 #puede asignar valores a las variables en su respectivo orden
print("primera forma de asignar valores a las variables")
print("variable uno",uno)
print("variable dos",dos)
print("variable tres",tres)
print("variable cuatro",cuatro)
print("segunda forma de asignar valores a las variables")
numeros=(4,5,6,7)
print(numeros)
uno, dos, tres, cuatro=numeros
print("variable uno",uno)
print("variable dos",dos)
print("variable tres",tres)
print("variable cuatro",cuatro)
print("tercera forma de asignar valores a las variables, los valores que sobran se asingan a la variable resto_valores")
numeros=(4,5,6,7,9,0,3)
uno, dos, tres, cuatro,*resto_valores=numeros # con * los valore que no tienen variables se asginan a resto_variables
print(numeros)
print("variable uno",uno)
print("variable dos",dos)
print("variable tres",tres)
print("variable cuatro",cuatro)
print("variable resto de valores",resto_valores)
print("cuarta forma de asignar valores a las variables, omitira los valores que no tengan variables y asi no generara error")
numeros=(4,5,6,7,9,0,3)
uno, dos, tres, cuatro,*_=numeros # con * los valore que no tienen variables se asginan a resto_variables
print(numeros)
print("variable uno",uno)
print("variable dos",dos)
print("variable tres",tres)
print("variable cuatro",cuatro)
print("quinta forma de asignar valores a las variables, omitira un rango de valores")
numeros=(1,2,3,4,5,6,7,8,9,10)
uno, _, tres, cuatro, *_, cinco, seis=numeros # con * los valore que no tienen variables se asginan a resto_variables
print(numeros)
print("variable uno",uno)
print("variable dos",dos)
print("variable tres",tres)
print("variable cuatro",cuatro)
print("variable cinco",cinco)
print("variable seis",seis)
