class ModeloConsultar():
    
    @classmethod #colocarlo
    def listar_consulta (self, conexOracle,asociado):
        try:
            cursor = conexOracle.connection.cursor()
            #sql = "select AP014.AANUMNIT, AP014.NNASOCIA , AP014.I_ESTASO from AP014MCLIENTE AP014 where AP014.AANUMNIT = '{0}'".format(asociado) # esta consulta funciona con le vista consultar1.html
            
            #sql = "select ap014.aanumnit, ap014.nnasocia, (select sum(pk_dr_vencimiento.FU_V_VENCIDO_DOCUMENTO(dr041mgdocumen.k_tipodr, dr041mgdocumen.k_numdoc,TRUNC(SYSDATE))) from dr041mgdocumen where dr041mgdocumen.k_tipodr = '1' and dr041mgdocumen.k_idterc = ap014.k_idterc and dr041mgdocumen.i_cancel = 'N')ven_aportes, (select sum(pk_dr_vencimiento.FU_V_VENCIDO_DOCUMENTO(dr041mgdocumen.k_tipodr, dr041mgdocumen.k_numdoc,TRUNC(SYSDATE))) from dr041mgdocumen where dr041mgdocumen.k_tipodr = '3' and dr041mgdocumen.k_idterc = ap014.k_idterc and dr041mgdocumen.i_cancel = 'N')ven_contractual, (select sum(pk_dr_vencimiento.FU_V_VENCIDO_DOCUMENTO(dr041mgdocumen.k_tipodr, dr041mgdocumen.k_numdoc,TRUNC(SYSDATE))) from dr041mgdocumen where dr041mgdocumen.k_tipodr = 'CMT' and dr041mgdocumen.k_idterc = ap014.k_idterc and dr041mgdocumen.i_cancel = 'N')ven_cuotamanejo, (select sum(PK_CA_FUNCION.FU_CONCEPTO('CAPITAL','VENCIDO',ca090mgsolcred.a_tipodr, ca090mgsolcred.a_obliga, TRUNC(SYSDATE), NULL,NULL)) from ca090mgsolcred where ap014.k_idterc = ca090mgsolcred.k_idterc and ca090mgsolcred.a_tipodr = '10' and PK_CA_FUNCION.FU_CONCEPTO('CAPITAL','SALDO',ca090mgsolcred.a_tipodr, ca090mgsolcred.a_obliga, TRUNC(SYSDATE), NULL,NULL)>0 and ca090mgsolcred.i_estsol = 'C' and ca090mgsolcred.i_anulad = 'N')ven_credito from ap014mcliente ap014 where ap014.AANUMNIT = '{0}' and PK_AP_AFILIACION.FU_CLIENTE_ACTIVO(AP014.K_IDTERC,TRUNC(SYSDATE))='ACTIVO'".format(asociado)
            sql = "select ap014.aanumnit, ap014.nnasocia, (select sum(pk_dr_vencimiento.FU_V_VENCIDO_DOCUMENTO(dr041mgdocumen.k_tipodr, dr041mgdocumen.k_numdoc, sysdate)) from dr041mgdocumen where dr041mgdocumen.k_tipodr = '1' and dr041mgdocumen.k_idterc = ap014.k_idterc and dr041mgdocumen.i_cancel = 'N')ven_aportes, (select sum(pk_dr_vencimiento.FU_V_VENCIDO_DOCUMENTO(dr041mgdocumen.k_tipodr, dr041mgdocumen.k_numdoc,sysdate)) from dr041mgdocumen where dr041mgdocumen.k_tipodr = '3' and dr041mgdocumen.k_idterc = ap014.k_idterc and dr041mgdocumen.i_cancel = 'N')ven_contractual, (select sum(pk_dr_vencimiento.FU_V_VENCIDO_DOCUMENTO(dr041mgdocumen.k_tipodr, dr041mgdocumen.k_numdoc,sysdate)) from dr041mgdocumen where dr041mgdocumen.k_tipodr = 'CMT' and dr041mgdocumen.k_idterc = ap014.k_idterc and dr041mgdocumen.i_cancel = 'N')ven_cuotamanejo, (select sum(PK_CA_FUNCION.FU_CONCEPTO('CAPITAL','VENCIDO',ca090mgsolcred.a_tipodr, ca090mgsolcred.a_obliga, sysdate, NULL,NULL)) from ca090mgsolcred where ap014.k_idterc = ca090mgsolcred.k_idterc and ca090mgsolcred.a_tipodr = '10' and PK_CA_FUNCION.FU_CONCEPTO('CAPITAL','SALDO',ca090mgsolcred.a_tipodr, ca090mgsolcred.a_obliga, sysdate, NULL,NULL)>0 and ca090mgsolcred.i_estsol = 'C' and ca090mgsolcred.i_anulad = 'N') + (select sum(PK_CA_FUNCION.FU_CONCEPTO('INTERES','VENCIDO',ca090mgsolcred.a_tipodr, ca090mgsolcred.a_obliga, sysdate, NULL,NULL)) from ca090mgsolcred where ap014.k_idterc = ca090mgsolcred.k_idterc and ca090mgsolcred.a_tipodr = '10' and PK_CA_FUNCION.FU_CONCEPTO('CAPITAL','SALDO',ca090mgsolcred.a_tipodr, ca090mgsolcred.a_obliga, sysdate, NULL,NULL)>0 and ca090mgsolcred.i_estsol = 'C' and ca090mgsolcred.i_anulad = 'N') + (select sum(PK_CA_FUNCION.FU_CONCEPTO('SEGURO_VIDA','VENCIDO',ca090mgsolcred.a_tipodr, ca090mgsolcred.a_obliga, sysdate, NULL,NULL)) from ca090mgsolcred where ap014.k_idterc = ca090mgsolcred.k_idterc and ca090mgsolcred.a_tipodr = '10' and PK_CA_FUNCION.FU_CONCEPTO('CAPITAL','SALDO',ca090mgsolcred.a_tipodr, ca090mgsolcred.a_obliga, sysdate, NULL,NULL)>0 and ca090mgsolcred.i_estsol = 'C' and ca090mgsolcred.i_anulad = 'N')ven_credito from ap014mcliente ap014 where ap014.AANUMNIT = '{0}' and PK_AP_AFILIACION.FU_CLIENTE_ACTIVO(AP014.K_IDTERC, sysdate)='ACTIVO'".format(asociado)
            cursor.execute(sql)
            data=cursor.fetchall()
            listaConsulta = []  #lista vacia
            for row in data:
                tuplaConsulta = row[0], row[1], row[2] , row[3] , row[4], row[5]# tupla
                #tuplaConsulta = row[0], row[1], row[2] # tupla
                listaConsulta.append(tuplaConsulta)  #llenando la lista
                #print(listaConsulta)
            return listaConsulta
        except Exception as ex:
            raise Exception (ex)